source 'https://rubygems.org'

gem 'bundler', '>= 2.7.2'
gem 'jekyll', '~> 4.4.1'
gem 'faraday', '~> 2.0.0'
gem 'faraday-retry', '~> 2.3.2'
gem 'csv'    
group :jekyll_plugins do
    gem 'jekyll-include-cache'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag', '~> 2.8'
    gem 'jekyll-sitemap'
    gem 'jekyll-octicons'
    gem 'jemoji'
    gem 'jekyll-github-metadata'
    gem 'jekyll-coffeescript'
    #gem 'jekyll-commonmark-ghpages'
    gem 'jekyll-gist'
    gem 'jekyll-paginate'
    gem 'jekyll-relative-links'
    gem 'jekyll-optional-front-matter'
    gem 'jekyll-readme-index'
    gem 'jekyll-default-layout'
    gem 'jekyll-titles-from-headings'
end
gem "webrick", "~> 1.9"