[build]
  publish = "_site"        # Jekyll’s output folder
  command = "bundle exec jekyll build"

[functions]
  directory = "netlify/functions"   # Where your serverless functions live

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200