bundle config set --local without 'development test'

[build]
  publish = "_site"        # Jekyll’s output folder
  command = "npm run build && bundle exec jekyll build --trace"

[context.production.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"   # Where your serverless functions live

[[redirects]]
  from = "https://bytelabsonline.netlify.app"
  to = "https://bytelabs.online"
  status = 301
  force = true