[[plugins]]
  package = "./plugins/netlify-purge-cloudflare-on-deploy"
  package = "netlify-plugin-jekyll-cache"


[build]
  publish = "_site"
  command = "npm run build && bundle config set --local without 'development test' && bundle exec jekyll build --trace"

[context.production.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"   # Where your serverless functions live

[[redirects]]
  from = "https://bytelabsonline.netlify.app"
  to = "https://bytelabs.online"
  status = 301
  force = true
