'use client';

import { useEffect, useRef, useState } from 'react';
import './Soundboard.css';

interface Sound {
  name: string;
  filename: string; // full or relative path to audio file
  category?: string;
}

export default function Soundboard() {
  const [sounds, setSounds] = useState<Sound[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const audioRef = useRef<Map<string, HTMLAudioElement>>(new Map());

  useEffect(() => {
    const fetchSounds = async () => {
      try {
        const response = await fetch('/soundboard.json');
        if (!response.ok) throw new Error('Failed to load sounds');
        const data = await response.json();
        // support two possible json shapes:
        // 1) { sounds: [ { name, filename } ] }
        // 2) [ { name, file } ] (generated by soundList.py)
        let items: any[] = [];
        if (Array.isArray(data)) {
          items = data;
        } else if (Array.isArray(data.sounds)) {
          items = data.sounds;
        }

        const parsed: Sound[] = items
          .map((it) => {
            const name = it.name || it.title || '';
            const filename = it.file || it.filename || it.path || '';
            return { name, filename } as Sound;
          })
          // filter out entries that are clearly not audio files
          .filter((s) => {
            const f = s.filename || '';
            if (!f) return false;
            // allow remote URLs
            if (f.startsWith('http')) return true;
            // allow explicit absolute or relative paths with common audio extensions
            return /\.(mp3|wav|ogg|m4a|flac)$/i.test(f);
          });

        setSounds(parsed);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
        console.error('Error loading soundboard:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchSounds();
  }, []);

  const playSound = async (filename: string) => {
    try {
      // build candidate URLs to try (absolute, origin-prefixed, api endpoint, or assets folder)
      const candidates: string[] = [];
      if (filename.startsWith('http')) candidates.push(filename);
      if (filename.startsWith('/')) candidates.push(window.location.origin + filename);
      // strip leading slashes for fallback
      const basename = filename.replace(/^\/+/, '');
      // try public assets folder
      candidates.push(`/assets/sounds/${basename}`);

      let foundSrc: string | null = null;
      for (const cand of candidates) {
        try {
          const res = await fetch(cand, { method: 'HEAD' });
          if (res.ok) {
            foundSrc = cand;
            break;
          }
        } catch (e) {
          // ignore and try next
        }
      }

      if (!foundSrc) {
        setError(`Sound file not found: ${filename}`);
        console.error('Sound file not found. Candidates tried:', candidates);
        return;
      }

      let audio = audioRef.current.get(foundSrc);
      if (!audio) {
        audio = new Audio(foundSrc);
        audioRef.current.set(foundSrc, audio);
      }

      audio.currentTime = 0;
      await audio.play();
    } catch (err) {
      console.error('Error playing sound:', err);
      setError('Error playing sound');
    }
  };

  if (loading) {
    return (
      <div className="soundboard-container">
        <div className="loading">$ LOADING SOUNDBOARD...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="soundboard-container">
        <div className="error">
          [ERROR] {error}
          <br />
          <small>Check that soundboard.json is generated in /public/</small>
        </div>
      </div>
    );
  }

  if (sounds.length === 0) {
    return (
      <div className="soundboard-container">
        <div className="no-sounds">
          $ NO SOUNDS FOUND
          <br />
          <small>Place audio files in ./assets/sounds/ and run soundList.py</small>
        </div>
      </div>
    );
  }

  return (
    <div className="soundboard-container">
      <h1 className="soundboard-title">&gt; SOUNDBOARD</h1>
      <div className="soundboard-grid">
        {sounds.map((sound) => (
          <button
            key={sound.filename}
            className="sound-button"
            onClick={() => playSound(sound.filename)}
            title={sound.name}
          >
            <span className="button-text">{sound.name}</span>
          </button>
        ))}
      </div>
    </div>
  );
}
